### ISSUE TITLE
This search backend does not work on the admin side

### ISSUE THREAD

**Issue by cho-leukeleu** [leukeleu/wagtail-pg-search-backend#19]
Hi,

We found out that this searchbackend does not work on the admin side (try searching a document for instance would always return 0 items).

It is though possible to choose to use this searchbackend only for frontend by slightly changing the settings to:

```
# Wagtail settings
WAGTAILSEARCH_BACKENDS = {
    'pg': {
        'BACKEND': 'wagtail_pgsearchbackend.backend',
        ...
    },
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.db',
        ...
    }
}
```

And then specifying the name of our preferred backend in the search app (views.py):

```
search_results = Page.objects.live().search(search_query, backend='pg')
```

**Comment by BertrandBordage** [comment]
I can’t reproduce this, everything works fine on my projects.

However, I think I know why you’re facing this.
Using the default PostgreSQL search configurations, filenames & paths are considered as an exact expression. So if the title of your document is `hello.pdf`, you can only find it by searching `hello.pdf`.

For example, if there is non-ASCII character in a filename, PostgreSQL will consider that it’s not a filename, so we can search for each word inside the filename:
```SQL
SELECT to_tsvector('french', 'quelle_bevue.pdf');
'quelle_bevue.pdf':1
```
```SQL
SELECT to_tsvector('french', 'quelle_bévue.pdf');
'bévue':2 'pdf': 3 'quell': 1
```
And since in wagtail-pg-search-backend we use unidecode to transcribe non-ASCII characters before sending to PostgreSQL, you’ll always be in the first case, except if your document title includes spaces and no extension, like `Quelle bévue`.

You can create your own search configuration to avoid this behaviour. Copy an existing search configuration, and remove [some PostgreSQL parsers](https://www.postgresql.org/docs/9.2/static/textsearch-parsers.html) like `url`, `host`, `url_path` & `file`.
