### ISSUE TITLE
Adding Partial Search and/or Trigram Search

### ISSUE THREAD

**Issue by griffint** [leukeleu/wagtail-pg-search-backend#20]
Is there a reason partial search matching is not supported beyond development resources? I'm interested in adding it to a project, and any advice for how that could be done would be very helpful!

**Comment by BertrandBordage** [comment]
The reason is the Wagtail API that was not designed for this. @kaedroho and I are currently redesigning this API to allow such features.

But it will never be available in this third-party app. This app was just created for this backend to be available until it was integrated in Wagtail. We’re keeping it alive for now for compatibility with previous versions, but we will soon remove it.

**Comment by BertrandBordage** [comment]
For those who would like to know how to unofficially do this for now, here is the stackoverflow ticket & answer from @griffint & I:
https://stackoverflow.com/questions/45864084/partial-matching-search-in-wagtail-with-postgres

**Comment by griffint** [comment]
Thanks so much for the fast and useful reply, this is good info to know. Do you have any idea of a timeline for when the API would have this sort of functionality? And is there a beta or development branch I could test out?

**Comment by BertrandBordage** [comment]
Unfortunately, the answers are no & no for now.
